DROP TABLE Balance CASCADE CONSTRAINTS;

DROP TABLE RoomState CASCADE CONSTRAINTS;

DROP TABLE KingRoom CASCADE CONSTRAINTS;

DROP TABLE TwinRoom CASCADE CONSTRAINTS;

DROP TABLE SingleRoom CASCADE CONSTRAINTS;

DROP TABLE Room CASCADE CONSTRAINTS;

DROP TABLE Reservation CASCADE CONSTRAINTS;

DROP TABLE Payment CASCADE CONSTRAINTS;

DROP TABLE Personnel_INFO CASCADE CONSTRAINTS;

DROP TABLE Personnel_ID CASCADE CONSTRAINTS;

DROP TABLE Passenger_INFO CASCADE CONSTRAINTS;

DROP TABLE Passenger_ID CASCADE CONSTRAINTS;